#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";

function usage() {
  throw new Error(
    "Usage: node embed_asset.mjs <input> <output> <identifier>",
  );
}

function escapeMoonBitLine(line) {
  return line.replace(/\r/g, "");
}

function main() {
  const [, , inputArg, outputArg, identifier] = process.argv;
  if (!inputArg || !outputArg || !identifier) {
    usage();
  }

  const inputPath = path.resolve(inputArg);
  const outputPath = path.resolve(outputArg);
  const text = fs.readFileSync(inputPath, "utf8");
  const lines = text.split(/\n/);

  const output = [
    "// Generated by runtime/embed_asset.mjs, do not edit.",
    "",
    "///|",
    `let ${identifier} : String =`,
    ...lines.map((line) => `  #|${escapeMoonBitLine(line)}`),
    "",
  ].join("\n");

  fs.writeFileSync(outputPath, output);
}

main();
