name: ci

on: [push, pull_request]

jobs:
  stable:
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          - macos-latest
          # - macos-13
          - windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup Moonbit
        uses: hustcer/setup-moonbit@v1
        with:
          version: latest

      - name: moon version
        run: |
          moon version --all

      - name: moon install
        run: |
          moon update
          moon install

      - name: moon check
        run: moon check --target native --deny-warn

      - name: format check
        run: |
          moon fmt --check

      - name: Setup MSVC
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run moon test (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          _CL_: /link /LIBPATH:lib webview.lib /DEBUG
          PATH: lib;${{ env.PATH }}
        run: |
          moon test --target native -C test

      # - name: Run moon test (non-windows)
      #   if: ${{ matrix.os != 'windows-latest' }}
      #   env:
      #     DYLD_LIBRARY_PATH: lib
      #   run: |
      #     moon test --target native -C test

      - name: moon test --doc (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          _CL_: /link /LIBPATH:lib webview.lib /DEBUG
          PATH: lib;${{ env.PATH }}
        run: |
          moon test --target native --doc

      - name: moon test --doc (non-windows)
        if: ${{ matrix.os != 'windows-latest' }}
        env:
          DYLD_LIBRARY_PATH: lib
        run: |
          moon test --target native --doc

      - name: moon build (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          _CL_: /link /LIBPATH:lib webview.lib /DEBUG
          PATH: lib;${{ env.PATH }}
        run: |
          moon build --target native -C examples

      - name: moon build (non-windows)
        if: ${{ matrix.os != 'windows-latest' }}
        env:
          DYLD_LIBRARY_PATH: lib
        run: |
          moon build --target native -C examples

      - name: check exe size
        if: ${{ matrix.os != 'windows-latest' }}
        run: find ./examples/target -name '*.exe' | xargs ls -lh

      - name: check core size on windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: Get-ChildItem -Path ".\examples\target" -Recurse -Filter "*.exe" | ForEach-Object { "{0} ({1} bytes)" -f $_.FullName, $_.Length }

  bleeding:
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          - macos-latest
          # - macos-13
          - windows-latest
    continue-on-error: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Moonbit
        uses: hustcer/setup-moonbit@v1
        with:
          version: bleeding

      - name: moon version
        run: |
          moon version --all

      - name: moon install
        run: |
          moon update
          moon install

      - name: Setup MSVC
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run moon test (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          _CL_: /link /LIBPATH:lib webview.lib /DEBUG
          PATH: lib;${{ env.PATH }}
        run: |
          moon test --target native -C test

      # - name: Run moon test (non-windows)
      #   if: ${{ matrix.os != 'windows-latest' }}
      #   env:
      #     DYLD_LIBRARY_PATH: lib
      #   run: |
      #     moon test --target native -C test

      - name: moon test --doc (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          _CL_: /link /LIBPATH:lib webview.lib /DEBUG
          PATH: lib;${{ env.PATH }}
        run: |
          moon test --target native --doc

      - name: moon test --doc (non-windows)
        if: ${{ matrix.os != 'windows-latest' }}
        env:
          DYLD_LIBRARY_PATH: lib
        run: |
          moon test --target native --doc

      - name: moon check
        run: moon check --target native

      - name: format check
        run: |
          moon fmt --check

      - name: moon build (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          _CL_: /link /LIBPATH:lib webview.lib /DEBUG
          PATH: lib;${{ env.PATH }}
        run: |
          moon build --target native -C examples

      - name: moon build (non-windows)
        if: ${{ matrix.os != 'windows-latest' }}
        env:
          DYLD_LIBRARY_PATH: lib
        run: |
          moon build --target native -C examples

      - name: check exe size
        if: ${{ matrix.os != 'windows-latest' }}
        run: find ./examples/target -name '*.exe' | xargs ls -lh

      - name: check core size on windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: Get-ChildItem -Path ".\examples\target" -Recurse -Filter "*.exe" | ForEach-Object { "{0} ({1} bytes)" -f $_.FullName, $_.Length }
